##
## EPITECH PROJECT, 2024
## Makefile
## File description:
## build and clear do_op
##

NAME = libmy.a

all: $(NAME)

$(NAME):
		make -C lib/my/
clean:
		make -C lib/my/ clean

fclean: clean
		make -C lib/my/ fclean

re: fclean $(NAME)
